
// Like a sign in sign out of the dapp idea -
// function that approves all required tokens on the dapp - like usdc, bonderPool token, bonderPool token lp, pairLp, yesTokens, noTokens....
// function that remove all allowances of required tokens on the dapp - like usdc, bonderPool token, bonderPool token lp, pairLp, yesTokens, noTokens....
